name: BlueCedarFilms
favicon: null
layout_spectrum: 0
typography_spectrum: 0
title: Blue Cedar
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#004670'
    - '#0085c7'
    - '#828282'
  brandStrength: 0.5
  lightness: 0.3125
  saturation: 0.9546613334678113
  rhythmicContrast: 0.5953322348650545
purpose: []
